/**
 * Maps Node Reasoner output → canvas-compatible child nodes.
 * Pure functions only — no API calls, no Gemini, no React.
 */

import type { AiGeneratedBranch } from "@/lib/agentExplore";
import type { AiDiscovery } from "@/types/discovery";
import type { CanvasNode } from "@/lib/worldBrain/mapArchitectureToCanvas";
import type {
  ContinuationDistance,
  DriftRisk,
  NodeReasonerOutput,
  PossibleNewNode,
  PossibleNodeContinuationType,
} from "@/lib/worldBrain/nodeReasonerTypes";

/** Synthetic agent id for nodes generated by the Node Reasoner layer. */
export const NODE_REASONER_AGENT_ID = "agent_node_reasoner";

export type NodeReasonerParentNode = {
  id: string;
  title?: string;
  displayTitle?: string;
};

/** Detail-panel metadata for a Node Reasoner child node. */
export type NodeReasonerNodePanelMeta = {
  fullTitle: string;
  displayTitle: string;
  discoveryQuestion: string;
  expansionPotential: string;
  continuationType: PossibleNodeContinuationType;
  continuationAnchor: string;
  continuationDistance: ContinuationDistance;
  whyThisFollows: string;
  noveltyScore: number;
  relevanceScore: number;
  continuityScore: number;
  driftRisk: DriftRisk;
  tags?: string[];
  sourceNodeId: string;
  sourceConstellationId: string;
  parentNodeId: string;
  depthLevel: number;
};

/** Canvas node extended with parent/depth for recursive expansion. */
export type NodeReasonerCanvasNode = CanvasNode & {
  parentNodeId: string;
  depthLevel: number;
};

export type MapNodeReasonerToCanvasParams = {
  output: NodeReasonerOutput;
  parentNode: NodeReasonerParentNode;
  selectedConstellationId: string;
  depthLevel?: number;
  existingNodeIds?: string[];
  generatedByAgentId?: string;
};

export type MapNodeReasonerToCanvasResult = {
  nodes: NodeReasonerCanvasNode[];
  panelMeta: Record<string, NodeReasonerNodePanelMeta>;
  nodeConstellationMap: Record<string, string>;
};

function sanitizeIdSegment(value: string): string {
  return (
    value
      .trim()
      .toLowerCase()
      .replace(/[^a-z0-9_]+/g, "_")
      .replace(/_+/g, "_")
      .replace(/^_|_$/g, "") || "node"
  );
}

/**
 * Deterministic unique id — never uses Math.random().
 * Preserves raw id when unused; otherwise prefixes with parent id.
 */
export function resolveNodeReasonerCanvasId(
  rawId: string,
  parentNodeId: string,
  index: number,
  taken: Set<string>,
): string {
  const trimmed = rawId.trim();
  const fallback = `subnode_${index + 1}`;
  const base = trimmed || fallback;
  const prefixed = `node_${sanitizeIdSegment(parentNodeId)}_${sanitizeIdSegment(base)}`;

  const candidates = base === trimmed && trimmed ? [base, prefixed] : [prefixed];

  for (const candidate of candidates) {
    if (candidate && !taken.has(candidate)) return candidate;
  }

  let suffix = 2;
  while (taken.has(`${prefixed}_${suffix}`)) {
    suffix++;
  }
  return `${prefixed}_${suffix}`;
}

function driftToRisk(drift: DriftRisk): string {
  return drift;
}

function buildPanelMeta(
  node: PossibleNewNode,
  canvasId: string,
  sourceNodeId: string,
  sourceConstellationId: string,
  parentNodeId: string,
  depthLevel: number,
): NodeReasonerNodePanelMeta {
  return {
    fullTitle: node.title.trim() || node.displayTitle.trim() || "Untitled Branch",
    displayTitle: node.displayTitle.trim() || node.title.trim() || "Untitled Branch",
    discoveryQuestion: node.discoveryQuestion,
    expansionPotential: node.expansionPotential,
    continuationType: node.continuationType,
    continuationAnchor: node.continuationAnchor,
    continuationDistance: node.continuationDistance,
    whyThisFollows: node.whyThisFollows,
    noveltyScore: node.noveltyScore,
    relevanceScore: node.relevanceScore,
    continuityScore: node.continuityScore,
    driftRisk: node.driftRisk,
    ...(node.tags && node.tags.length > 0 ? { tags: [...node.tags] } : {}),
    sourceNodeId,
    sourceConstellationId,
    parentNodeId,
    depthLevel,
  };
}

/** Maps one PossibleNewNode → canvas node + panel meta. Pure, no mutation. */
export function mapPossibleNewNodeToCanvasNode(
  node: PossibleNewNode,
  params: {
    canvasId: string;
    parentNodeId: string;
    constellationId: string;
    depthLevel: number;
    sourceNodeId: string;
    sourceConstellationId: string;
    generatedByAgentId?: string;
  },
): { canvasNode: NodeReasonerCanvasNode; panelMeta: NodeReasonerNodePanelMeta } {
  const fullTitle = node.title.trim() || node.displayTitle.trim() || "Untitled Branch";
  const discoveryQuestion = node.discoveryQuestion.trim();
  const explorationQuestions = discoveryQuestion ? [discoveryQuestion] : [];

  const canvasNode: NodeReasonerCanvasNode = {
    id: params.canvasId,
    title: fullTitle,
    description: node.description,
    constellationId: params.constellationId,
    generatedByAgentId: params.generatedByAgentId ?? NODE_REASONER_AGENT_ID,
    whyPromising: node.whyThisFollows.trim() || node.expansionPotential.trim(),
    risk: driftToRisk(node.driftRisk),
    explorationQuestions,
    nodeType: node.nodeType,
    status: "potential",
    aiGenerated: true,
    parentNodeId: params.parentNodeId,
    depthLevel: params.depthLevel,
  };

  const panelMeta = buildPanelMeta(
    node,
    params.canvasId,
    params.sourceNodeId,
    params.sourceConstellationId,
    params.parentNodeId,
    params.depthLevel,
  );

  return { canvasNode, panelMeta };
}

/** Maps NodeReasonerOutput.possibleNewNodes → canvas-compatible child nodes. */
export function mapNodeReasonerOutputToCanvasNodes(
  params: MapNodeReasonerToCanvasParams,
): MapNodeReasonerToCanvasResult {
  const {
    output,
    parentNode,
    selectedConstellationId,
    depthLevel: depthOverride,
    existingNodeIds = [],
    generatedByAgentId,
  } = params;

  // Canvas parent id is authoritative — LLM sourceNodeId can drift and break Galaxy moon anchoring.
  const parentNodeId = parentNode.id.trim();
  const sourceNodeId = parentNodeId || output.sourceNodeId.trim();
  const sourceConstellationId =
    (output.sourceConstellationId ?? "").trim() || selectedConstellationId.trim();
  const depthLevel = depthOverride ?? Math.max(2, output.suggestedDepth ?? 2);

  const taken = new Set<string>(existingNodeIds);
  const nodes: NodeReasonerCanvasNode[] = [];
  const panelMeta: Record<string, NodeReasonerNodePanelMeta> = {};
  const nodeConstellationMap: Record<string, string> = {};

  output.possibleNewNodes.forEach((possibleNode, index) => {
    const canvasId = resolveNodeReasonerCanvasId(
      possibleNode.id,
      parentNodeId,
      index,
      taken,
    );
    taken.add(canvasId);

    const constellationId =
      (possibleNode.sourceConstellationId ?? "").trim() || sourceConstellationId;

    const { canvasNode, panelMeta: meta } = mapPossibleNewNodeToCanvasNode(
      possibleNode,
      {
        canvasId,
        parentNodeId,
        constellationId,
        depthLevel,
        sourceNodeId,
        sourceConstellationId,
        generatedByAgentId,
      },
    );

    nodes.push(canvasNode);
    panelMeta[canvasId] = meta;
    nodeConstellationMap[canvasId] = constellationId;
  });

  return { nodes, panelMeta, nodeConstellationMap };
}

/** Register Node Reasoner child labels for canvas title resolution. */
export function registerNodeReasonerNodeMeta(
  panelMeta: Record<string, NodeReasonerNodePanelMeta>,
  register: (entries: Array<{ id: string; displayTitle: string; nodeType: string }>) => void,
): void {
  const entries = Object.entries(panelMeta).map(([id, meta]) => ({
    id,
    displayTitle: meta.displayTitle,
    nodeType: "continuation",
  }));
  register(entries);
}

/** Maps a Node Reasoner canvas node → AiGeneratedBranch for the exploration graph. */
export function nodeReasonerCanvasNodeToAiBranch(
  node: NodeReasonerCanvasNode,
  meta: NodeReasonerNodePanelMeta,
  parentId: string,
): AiGeneratedBranch {
  return {
    id: node.id,
    title: meta.displayTitle,
    description: node.description,
    whyItMatters: meta.whyThisFollows || meta.discoveryQuestion,
    domain: node.nodeType,
    sourceAgent: "Node Reasoner",
    rippleHint: meta.expansionPotential,
    crossDomainEffects: [],
    continuityRisk:
      meta.driftRisk === "high" ? "high" : meta.driftRisk === "low" ? "low" : "medium",
    qualityScore: Math.min(1, meta.continuityScore / 10),
    parentId,
    generated: true,
  };
}

/** Maps a Node Reasoner branch → AiDiscovery for the detail panel. */
export function nodeReasonerBranchToAiDiscovery(
  branch: AiGeneratedBranch,
  meta?: NodeReasonerNodePanelMeta,
): AiDiscovery {
  return {
    id: branch.id,
    title: meta?.fullTitle ?? branch.title,
    description: branch.description,
    category: branch.domain,
    whyItMatters: meta?.whyThisFollows ?? branch.whyItMatters,
    sourceAgent: branch.sourceAgent,
    rippleHint: meta?.expansionPotential ?? branch.rippleHint,
    generated: true,
    whyPromising: meta?.whyThisFollows ?? branch.whyItMatters,
    explorationQuestions: meta?.discoveryQuestion
      ? [meta.discoveryQuestion]
      : undefined,
    nodeType: branch.domain,
  };
}
